### ISSUE TITLE
fix positioning of balloons in horizontal gauge - they overlap when collaboration and autarky are close together and/or are close to 0 or max

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#86] opened 2023-11-13 08:34 UTC
The balloons that indicate the values for collaboration and autarky in the horizontal gauge sometimes overlap. Their positioning must be improved - catering for:

* coll and aut are close together
* collab and/or aut are close to max
* collab and/or aut are close to min

![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/00a474f8-0604-432b-9781-62c90c09f683)

![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/beedcf15-d54b-42e9-93fd-8748be5fad68)

**Comment by lucasjellema** [comment] 2023-11-14 14:08
i think this is fixed - at least good enough


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/67c76dab-9f0c-4234-8bb0-9d0912f0f4cd)

**Comment by OmNomNomzzz** [comment] 2023-11-20 07:36
The issue is fixed. Able to see things properly. Agreed. It is good enough for the pilot project.

**Comment by OmNomNomzzz** [comment] 2023-11-20 15:41
Happy to close this issue as I feel it is solve sufficiently well.

**Closed by OmNomNomzzz** 2023-11-20 15:41 UTC
Labels: Medium priority, Front End, Peer Review
